/** Fallback nemesis names — used when LM Studio is unavailable */
export const FALLBACK_NEMESIS_NAMES: readonly string[] = [
  'Vorreth',
  'Skullmaw',
  'Grethak',
  'Ironjaw',
  'Mordusk',
  'Blightfang',
  'Ravenwrath',
  'Grimhowl',
  'Ashclaw',
  'Dreadmaw',
  'Thornspite',
  'Soulrender',
  'Blackthorn',
  'Wraithborn',
  'Cinderscale',
  'Hexmaw',
  'Ruinblight',
  'Voreclaw',
  'Duskwhisper',
  'Netherfang',
];

/** Fallback nemesis titles/epithets */
export const FALLBACK_NEMESIS_TITLES: readonly string[] = [
  'the Unbroken',
  'Devourer of Light',
  'the Bloodless',
  'Scourge of the Deep',
  'the Undying',
  'Bane of the Living',
  'the Relentless',
  'Harbinger of Ruin',
  'the Hollow',
  'Crusher of Hope',
  'the Forsaken',
  'Terror of the Depths',
  'the Inexorable',
  'Plague of the Dungeon',
  'the Ancient Wrath',
  'Heir to Darkness',
  'the Merciless',
  'Eater of Souls',
  'the Cursed',
  'Doom of the Fallen',
  'the Shadowed Warden',
  'the Silent Maw',
  'the Unforgiven',
  'the Ashen Reaper',
  'the Void-Seeker',
  'the Iron-Hearted',
  'the Eternal Maw',
  'Bloodless Sovereign',
];

/** Fallback nemesis rumors for town gossip */
export const FALLBACK_NEMESIS_RUMORS: readonly string[] = [
  'They say the creature that stalks the catacombs has eyes like burning coals; every torch it passes goes dark.',
  'Whispers claim the beast\'s claws can rend stone as easily as paper — no armor will hold against its talons.',
  'Some swear they heard it laugh, a sound that turns bone to ice and makes even the bravest heart shiver.',
  'They say the creature feeds on fear itself; those who enter its lair leave with their souls hollowed out.',
  'It is rumored the beast can mimic any voice, luring wanderers deeper until they never return.',
  'They speak of a night when the beast walked straight through walls, leaving only scorched earth behind.',
  'Some fear the creature\'s touch turns flesh to stone; even brave warriors have been found frozen mid-battle.',
  'The beast grows stronger with every death it claims — its hunger never sated, its rage ever rising.',
  'If you hear the creature\'s footsteps echoing in your mind, you are already lost.',
  'A survivor spoke of red eyes in the dark, watching — always watching — before they fled screaming.',
];
