import type { ArmorTemplate } from '@dungeon/contracts';
import { ENCHANTMENT_SLOTS_BY_RARITY } from '../balance/tables.js';

function slots(rarity: string, enchantments: (string | null)[] = []): { enchantmentSlots: number; enchantments: readonly (string | null)[] } {
  const count = ENCHANTMENT_SLOTS_BY_RARITY[rarity] ?? 0;
  const nulls = Array.from({ length: Math.max(0, count - enchantments.length) }, () => null);
  return { enchantmentSlots: count, enchantments: [...enchantments, ...nulls] };
}

export const ARMOR: readonly ArmorTemplate[] = [
  // === CHEST ===
  {
    itemId: 'leather_vest',
    name: 'Leather Vest',
    description: 'Basic leather protection.',
    itemClass: 'armor',
    rarity: 'common',
    value: 12,
    stackable: false,
    maxStack: 1,
    armor: { defense: 2, evasionPenalty: 0, slot: 'chest', ...slots('common') },
  },
  {
    itemId: 'chain_shirt',
    name: 'Chain Shirt',
    description: 'Linked metal rings offering decent protection.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 35,
    stackable: false,
    maxStack: 1,
    armor: { defense: 5, evasionPenalty: 5, slot: 'chest', ...slots('uncommon') },
  },
  {
    itemId: 'plate_armor',
    name: 'Plate Armor',
    description: 'Heavy metal plates. Excellent defense, poor mobility.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 70,
    stackable: false,
    maxStack: 1,
    armor: { defense: 10, evasionPenalty: 15, slot: 'chest', ...slots('rare') },
  },
  {
    itemId: 'fire_ward_cloak',
    name: 'Fire Ward Cloak',
    description: 'A cloak woven with fire-resistant fibers.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 40,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 0, slot: 'chest', resistance: { fire: 0.3 }, ...slots('uncommon') },
  },
  {
    itemId: 'regen_vest',
    name: 'Regen Vest',
    description: 'A vest imbued with regenerative magic.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 90,
    stackable: false,
    maxStack: 1,
    armor: { defense: 8, evasionPenalty: 0, slot: 'chest', ...slots('rare', ['hp_regen']) },
  },

  // === HEAD ===
  {
    itemId: 'leather_cap',
    name: 'Leather Cap',
    description: 'A simple leather cap.',
    itemClass: 'armor',
    rarity: 'common',
    value: 8,
    stackable: false,
    maxStack: 1,
    armor: { defense: 1, evasionPenalty: 0, slot: 'head', ...slots('common') },
  },
  {
    itemId: 'iron_helm',
    name: 'Iron Helm',
    description: 'A solid iron helmet.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 28,
    stackable: false,
    maxStack: 1,
    armor: { defense: 4, evasionPenalty: 3, slot: 'head', ...slots('uncommon') },
  },

  // === GLOVES ===
  {
    itemId: 'leather_gloves',
    name: 'Leather Gloves',
    description: 'Simple leather hand protection.',
    itemClass: 'armor',
    rarity: 'common',
    value: 7,
    stackable: false,
    maxStack: 1,
    armor: { defense: 1, evasionPenalty: 0, slot: 'gloves', ...slots('common') },
  },
  {
    itemId: 'chain_gauntlets',
    name: 'Chain Gauntlets',
    description: 'Mail gauntlets for solid hand defense.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 22,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 2, slot: 'gloves', ...slots('uncommon') },
  },

  // === BOOTS ===
  {
    itemId: 'leather_boots',
    name: 'Leather Boots',
    description: 'Basic leather footwear.',
    itemClass: 'armor',
    rarity: 'common',
    value: 8,
    stackable: false,
    maxStack: 1,
    armor: { defense: 1, evasionPenalty: 0, slot: 'boots', ...slots('common') },
  },
  {
    itemId: 'steel_sabatons',
    name: 'Steel Sabatons',
    description: 'Heavy steel foot armor.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 55,
    stackable: false,
    maxStack: 1,
    armor: { defense: 5, evasionPenalty: 5, slot: 'boots', ...slots('rare') },
  },

  // === RING ===
  {
    itemId: 'copper_ring',
    name: 'Copper Ring',
    description: 'A plain copper ring, suitable for enchanting.',
    itemClass: 'armor',
    rarity: 'common',
    value: 10,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('common') },
  },
  {
    itemId: 'silver_band',
    name: 'Silver Band',
    description: 'A silver ring with one enchantment slot.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 30,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('uncommon') },
  },

  // === NEW ENCHANTED ITEMS (D4) ===

  // Chest armor
  {
    itemId: 'spiked_leather',
    name: 'Spiked Leather',
    description: 'Leather armor with sharp spikes protruding from the surface.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 45,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 0, slot: 'chest', ...slots('uncommon', ['thorns']) },
  },
  {
    itemId: 'ember_cloak',
    name: 'Ember Cloak',
    description: 'A cloak that radiates heat and grants regeneration.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 95,
    stackable: false,
    maxStack: 1,
    armor: { defense: 5, evasionPenalty: 0, slot: 'chest', ...slots('rare', ['resist_fire', 'hp_regen']) },
  },
  {
    itemId: 'shadow_vest',
    name: 'Shadow Vest',
    description: 'A dark vest that enables brief moments of teleportation.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 100,
    stackable: false,
    maxStack: 1,
    armor: { defense: 4, evasionPenalty: 0, slot: 'chest', ...slots('rare', ['blink']) },
  },
  {
    itemId: 'bone_guard_plate',
    name: 'Bone Guard Plate',
    description: 'Heavy plate crafted from bone, with sharp edges.',
    itemClass: 'armor',
    rarity: 'epic',
    value: 150,
    stackable: false,
    maxStack: 1,
    armor: { defense: 12, evasionPenalty: 10, slot: 'chest', ...slots('epic', ['thorns', 'defense_boost']) },
  },
  {
    itemId: 'plague_mantle',
    name: 'Plague Mantle',
    description: 'A tattered mantle that grants poison resistance.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 40,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 0, slot: 'chest', ...slots('uncommon', ['blight_ward']) },
  },

  // Head armor
  {
    itemId: 'warden_helm',
    name: 'Warden Helm',
    description: 'A sturdy helmet that improves defense.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 35,
    stackable: false,
    maxStack: 1,
    armor: { defense: 5, evasionPenalty: 2, slot: 'head', ...slots('uncommon', ['defense_boost']) },
  },
  {
    itemId: 'iron_crown',
    name: 'Iron Crown',
    description: 'A regal crown of pure iron with enhanced defenses.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 85,
    stackable: false,
    maxStack: 1,
    armor: { defense: 7, evasionPenalty: 4, slot: 'head', ...slots('rare', ['defense_boost']) },
  },
  {
    itemId: 'mind_veil',
    name: 'Mind Veil',
    description: 'A mystical veil that protects against magical ailments.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 90,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 0, slot: 'head', ...slots('rare', ['blight_ward']) },
  },

  // Boots
  {
    itemId: 'swift_boots',
    name: 'Swift Boots',
    description: 'Enchanted boots that enhance movement speed.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 38,
    stackable: false,
    maxStack: 1,
    armor: { defense: 1, evasionPenalty: 0, slot: 'boots', ...slots('uncommon', ['speed_boost']) },
  },
  {
    itemId: 'phase_steps',
    name: 'Phase Steps',
    description: 'Boots that allow brief teleportation and enhanced evasion.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 98,
    stackable: false,
    maxStack: 1,
    armor: { defense: 2, evasionPenalty: 0, slot: 'boots', ...slots('rare', ['blink', 'evasion_boost']) },
  },

  // Gloves
  {
    itemId: 'grip_gauntlets',
    name: 'Grip Gauntlets',
    description: 'Reinforced gauntlets that improve defensive capabilities.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 32,
    stackable: false,
    maxStack: 1,
    armor: { defense: 4, evasionPenalty: 2, slot: 'gloves', ...slots('uncommon', ['defense_boost']) },
  },
  {
    itemId: 'leech_wraps',
    name: 'Leech Wraps',
    description: 'Mystical wraps that steal vitality from enemies.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 88,
    stackable: false,
    maxStack: 1,
    armor: { defense: 3, evasionPenalty: 0, slot: 'gloves', ...slots('rare', ['life_steal']) },
  },

  // Rings
  {
    itemId: 'venom_ring',
    name: 'Venom Ring',
    description: 'A ring that grants poison resistance.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 28,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('uncommon', ['resist_poison']) },
  },
  {
    itemId: 'blessed_ring',
    name: 'Blessed Ring',
    description: 'A holy ring that grants slow regeneration.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 72,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('rare', ['hp_regen']) },
  },
  {
    itemId: 'iron_band',
    name: 'Iron Band',
    description: 'A sturdy iron ring that enhances defense.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 26,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('uncommon', ['defense_boost']) },
  },
  {
    itemId: 'ember_ring',
    name: 'Ember Ring',
    description: 'A ring wreathed in flames, granting fire resistance.',
    itemClass: 'armor',
    rarity: 'uncommon',
    value: 29,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('uncommon', ['resist_fire']) },
  },
  {
    itemId: 'shadow_ring',
    name: 'Shadow Ring',
    description: 'A dark ring that enables evasion and teleportation.',
    itemClass: 'armor',
    rarity: 'rare',
    value: 85,
    stackable: false,
    maxStack: 1,
    armor: { defense: 0, evasionPenalty: 0, slot: 'ring', ...slots('rare', ['blink', 'evasion_boost']) },
  },
];
