import type { ConsumableTemplate } from '@dungeon/contracts';

export const CONSUMABLES: readonly ConsumableTemplate[] = [
  {
    itemId: 'health_potion',
    name: 'Health Potion',
    description: 'Restores 30 health.',
    itemClass: 'consumable',
    rarity: 'common',
    value: 10,
    stackable: true,
    maxStack: 5,
    consumable: { effect: 'heal', magnitude: 30 },
  },
  {
    itemId: 'greater_health_potion',
    name: 'Greater Health Potion',
    description: 'Restores 60 health.',
    itemClass: 'consumable',
    rarity: 'uncommon',
    value: 25,
    stackable: true,
    maxStack: 3,
    consumable: { effect: 'heal', magnitude: 60 },
  },
  {
    itemId: 'antidote',
    name: 'Antidote',
    description: 'Cures poison.',
    itemClass: 'consumable',
    rarity: 'common',
    value: 8,
    stackable: true,
    maxStack: 5,
    consumable: { effect: 'cure', magnitude: 0, targetStatus: 'poison' },
  },
  {
    itemId: 'strength_elixir',
    name: 'Strength Elixir',
    description: 'Temporarily boosts attack power.',
    itemClass: 'consumable',
    rarity: 'uncommon',
    value: 20,
    stackable: true,
    maxStack: 3,
    consumable: { effect: 'buff', magnitude: 5, duration: 10 },
  },
  {
    itemId: 'bomb',
    name: 'Bomb',
    description: 'Deals 25 fire damage to an adjacent enemy.',
    itemClass: 'consumable',
    rarity: 'uncommon',
    value: 15,
    stackable: true,
    maxStack: 3,
    consumable: { effect: 'damage', magnitude: 25 },
  },
];
