import type { TrapItemTemplate } from '@dungeon/contracts';
import { TRAP_SPIKES_RARITY } from '../objects/trap-spikes.js';
import { FIRE_PIT_RARITY } from '../objects/fire-pit.js';
import { POISON_TRAP_RARITY } from '../objects/poison-trap.js';
import { FROST_TRAP_RARITY } from '../objects/frost-trap.js';
import { LIGHTNING_TRAP_RARITY } from '../objects/lightning-trap.js';
import { INFERNO_PIT_RARITY } from '../objects/inferno-pit.js';

export const TRAPS: readonly TrapItemTemplate[] = [
  // Spike trap variants
  {
    itemId: 'wooden_spike_trap',
    name: 'Wooden Spike Trap',
    description: 'A simple spike trap. Causes bleeding when triggered.',
    itemClass: 'trap',
    rarity: TRAP_SPIKES_RARITY,
    value: 15,
    stackable: true,
    maxStack: 5,
    trapTemplateId: 'trap_spikes',
  },
  {
    itemId: 'iron_spike_trap',
    name: 'Iron Spike Trap',
    description: 'A reinforced spike trap. Deals more damage and causes bleeding.',
    itemClass: 'trap',
    rarity: 'uncommon',
    value: 30,
    stackable: true,
    maxStack: 3,
    trapTemplateId: 'trap_spikes',
  },
  {
    itemId: 'steel_spike_trap',
    name: 'Steel Spike Trap',
    description: 'A finely crafted spike trap. Devastating to those who trigger it.',
    itemClass: 'trap',
    rarity: TRAP_SPIKES_RARITY,
    value: 60,
    stackable: true,
    maxStack: 2,
    trapTemplateId: 'trap_spikes',
  },

  // Fire trap variants
  {
    itemId: 'fire_trap',
    name: 'Fire Trap',
    description: 'A trap that ignites on contact. Sets targets ablaze.',
    itemClass: 'trap',
    rarity: FIRE_PIT_RARITY,
    value: 15,
    stackable: true,
    maxStack: 5,
    trapTemplateId: 'fire_pit',
  },
  {
    itemId: 'inferno_trap',
    name: 'Inferno Trap',
    description: 'A powerful fire trap that burns with intense heat.',
    itemClass: 'trap',
    rarity: FIRE_PIT_RARITY,
    value: 30,
    stackable: true,
    maxStack: 3,
    trapTemplateId: 'fire_pit',
  },
  {
    itemId: 'blazing_trap',
    name: 'Blazing Trap',
    description: 'An infernal trap that engulfs targets in flames.',
    itemClass: 'trap',
    rarity: INFERNO_PIT_RARITY,
    value: 60,
    stackable: true,
    maxStack: 2,
    trapTemplateId: 'fire_pit',
  },

  // Poison trap variants
  {
    itemId: 'poison_gas_trap',
    name: 'Poison Gas Trap',
    description: 'Releases toxic gas. Poisons those who trigger it.',
    itemClass: 'trap',
    rarity: POISON_TRAP_RARITY,
    value: 30,
    stackable: true,
    maxStack: 3,
    trapTemplateId: 'poison_trap',
  },
  {
    itemId: 'toxic_trap',
    name: 'Toxic Trap',
    description: 'A highly toxic trap that spreads poisonous fumes.',
    itemClass: 'trap',
    rarity: POISON_TRAP_RARITY,
    value: 60,
    stackable: true,
    maxStack: 2,
    trapTemplateId: 'poison_trap',
  },
  {
    itemId: 'lethal_poison_trap',
    name: 'Lethal Poison Trap',
    description: 'A deadly trap with concentrated venom.',
    itemClass: 'trap',
    rarity: POISON_TRAP_RARITY,
    value: 150,
    stackable: true,
    maxStack: 1,
    trapTemplateId: 'poison_trap',
  },

  // Frost trap variants
  {
    itemId: 'frost_trap',
    name: 'Frost Trap',
    description: 'An icy trap that slows those who trigger it.',
    itemClass: 'trap',
    rarity: FROST_TRAP_RARITY,
    value: 30,
    stackable: true,
    maxStack: 3,
    trapTemplateId: 'frost_trap',
  },
  {
    itemId: 'frozen_trap',
    name: 'Frozen Trap',
    description: 'A powerful frost trap that freezes targets.',
    itemClass: 'trap',
    rarity: FROST_TRAP_RARITY,
    value: 60,
    stackable: true,
    maxStack: 2,
    trapTemplateId: 'frost_trap',
  },
  {
    itemId: 'absolute_zero_trap',
    name: 'Absolute Zero Trap',
    description: 'A trap of ultimate cold that completely immobilizes targets.',
    itemClass: 'trap',
    rarity: FROST_TRAP_RARITY,
    value: 150,
    stackable: true,
    maxStack: 1,
    trapTemplateId: 'frost_trap',
  },

  // Lightning trap variants
  {
    itemId: 'lightning_trap',
    name: 'Lightning Trap',
    description: 'An electrical trap that stuns those who trigger it.',
    itemClass: 'trap',
    rarity: LIGHTNING_TRAP_RARITY,
    value: 60,
    stackable: true,
    maxStack: 2,
    trapTemplateId: 'lightning_trap',
  },
  {
    itemId: 'thunder_trap',
    name: 'Thunder Trap',
    description: 'A powerful electrical trap that shocks the area.',
    itemClass: 'trap',
    rarity: LIGHTNING_TRAP_RARITY,
    value: 150,
    stackable: true,
    maxStack: 1,
    trapTemplateId: 'lightning_trap',
  },

  // Inferno pit (epic fire)
  {
    itemId: 'epic_inferno_pit',
    name: 'Epic Inferno Pit',
    description: 'The ultimate fire trap. Immense heat and flames consume all.',
    itemClass: 'trap',
    rarity: INFERNO_PIT_RARITY,
    value: 150,
    stackable: true,
    maxStack: 1,
    trapTemplateId: 'inferno_pit',
  },
];
