import type { WeaponTemplate } from '@dungeon/contracts';

export const WEAPONS: readonly WeaponTemplate[] = [
  {
    itemId: 'rusty_sword',
    name: 'Rusty Sword',
    description: 'A worn but functional blade.',
    itemClass: 'weapon',
    rarity: 'common',
    value: 15,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 3, damageType: 'physical', accuracy: 5, speed: 0, slot: 'weapon', weaponRange: 1, weaponType: 'blade' },
  },
  {
    itemId: 'iron_mace',
    name: 'Iron Mace',
    description: 'A heavy mace that hits hard but slow.',
    itemClass: 'weapon',
    rarity: 'common',
    value: 20,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 5, damageType: 'physical', accuracy: -5, speed: -5, slot: 'weapon', weaponRange: 1, weaponType: 'bludgeon' },
  },
  {
    itemId: 'short_bow',
    name: 'Short Bow',
    description: 'A simple ranged weapon. Can attack from up to 5 tiles away.',
    itemClass: 'weapon',
    rarity: 'common',
    value: 18,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 3, damageType: 'physical', accuracy: 10, speed: 5, slot: 'weapon', weaponRange: 5, minRange: 2, weaponType: 'ranged' },
  },
  {
    itemId: 'flame_dagger',
    name: 'Flame Dagger',
    description: 'A dagger that burns on contact.',
    itemClass: 'weapon',
    rarity: 'uncommon',
    value: 45,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 5, damageType: 'fire', accuracy: 10, speed: 10, slot: 'weapon', weaponRange: 1, weaponType: 'blade', onHitStatus: 'burn', onHitChance: 20 },
  },
  {
    itemId: 'venom_blade',
    name: 'Venom Blade',
    description: 'A wicked blade coated in poison.',
    itemClass: 'weapon',
    rarity: 'uncommon',
    value: 50,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 6, damageType: 'physical', accuracy: 5, speed: 5, slot: 'weapon', weaponRange: 1, weaponType: 'blade', onHitStatus: 'poison', onHitChance: 25 },
  },
  {
    itemId: 'frost_axe',
    name: 'Frost Axe',
    description: 'An axe wreathed in cold.',
    itemClass: 'weapon',
    rarity: 'rare',
    value: 80,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 10, damageType: 'frost', accuracy: 0, speed: 0, slot: 'weapon', weaponRange: 1, weaponType: 'axe', onHitStatus: 'slow', onHitChance: 30 },
  },
  // 4 new weapons
  {
    itemId: 'hand_axe',
    name: 'Hand Axe',
    description: 'A light axe balanced for throwing or swinging.',
    itemClass: 'weapon',
    rarity: 'common',
    value: 16,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 4, damageType: 'physical', accuracy: 0, speed: 0, slot: 'weapon', weaponRange: 1, weaponType: 'axe' },
  },
  {
    itemId: 'war_bow',
    name: 'War Bow',
    description: 'A powerful longbow with exceptional range.',
    itemClass: 'weapon',
    rarity: 'uncommon',
    value: 55,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 6, damageType: 'physical', accuracy: 5, speed: 0, slot: 'weapon', weaponRange: 6, minRange: 2, weaponType: 'ranged' },
  },
  {
    itemId: 'iron_sword',
    name: 'Iron Sword',
    description: 'A reliable blade forged from quality iron.',
    itemClass: 'weapon',
    rarity: 'rare',
    value: 75,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 10, damageType: 'physical', accuracy: 5, speed: 5, slot: 'weapon', weaponRange: 1, weaponType: 'blade' },
  },
  {
    itemId: 'stone_hammer',
    name: 'Stone Hammer',
    description: 'A brutal hammer that weakens foes on impact.',
    itemClass: 'weapon',
    rarity: 'uncommon',
    value: 40,
    stackable: false,
    maxStack: 1,
    weapon: { damage: 7, damageType: 'physical', accuracy: -5, speed: -5, slot: 'weapon', weaponRange: 1, weaponType: 'bludgeon', onHitStatus: 'weaken', onHitChance: 20 },
  },
];
