/**
 * Animation references — the authoritative catalog of animation tokens.
 *
 * Organized by visual category. Each category exports AnimationRef objects.
 * The generator discovers all refs and emits the grouped animationRefs object below.
 *
 * NOTE: This file is hand-stubbed during Phase 0 and converted to generated output
 * once the generator is extended. Authors do not edit this file directly after Phase 0.
 */

/**
 * The canonical animation reference catalog.
 *
 * Usage:
 *   animation: { id: animationRefs.impact.radialImpactBurst.id }
 *   overlay: { id: animationRefs.status.goldRingPulse.id }
 *
 * Every animation ID literal (fx.category.name) is declared here.
 * All other consumers must dot-walk through this object.
 */

import { healingPulse, staminaSurge, cureSparkle } from './self.js';
import { bombBlast } from './aoe.js';
import { goldRingPulse } from './status.js';

export const animationRefs = {
  impact: {},
  projectile: {},
  self: {
    healingPulse,
    staminaSurge,
    cureSparkle,
  },
  aoe: {
    bombBlast,
  },
  status: {
    goldRingPulse,
  },
  utility: {},
} as const;


/** Flat O(1) lookup map of all animation refs by ID. Used by the presenter for fast ref resolution. */
export const ANIMATION_REF_BY_ID = new Map(
  [
    ...Object.values(animationRefs.self),
    ...Object.values(animationRefs.aoe),
    ...Object.values(animationRefs.status),
  ].map(ref => [ref.id, ref] as const)
);

export type { AnimationRef, AnimationId, AnimationCategory } from './types.js';
