export { resolveAttack } from './combat.js';
export { validateMove, isWalkable } from './movement.js';
export { computeFov } from './fov.js';
export { decideEnemyAction } from './enemy-ai.js';
export { addItemToInventory, removeItemFromInventory, useConsumable } from './inventory.js';
export { calculateEquippedStats, equipItem, unequipItem, swapWeaponSets } from './equipment.js';
export { applyStatusToPlayer, applyStatusToEnemy, tickPlayerStatuses, getEffectiveStat, hasStatus, } from './status-effects.js';
export { processEnemyLoot, rollGoldDrop, rollItemDrop, rollNemesisLoot } from './loot.js';
export { canRetreat, executeRetreat } from './retreat.js';
export { handlePlayerDeath } from './death.js';
export { processTownAction } from './town.js';
export { processTalkNpc, updateNpcDisposition } from './npc.js';
export { checkLevelUp } from './progression.js';
export { shouldPromoteToNemesis, promoteToNemesis, slayNemesis, findNemesisByTemplateId } from './nemesis.js';
export { grantAbility, canUseAbility, tickAbilityCooldowns } from './abilities.js';
export { getValidTrapPlacementDirections } from './trap-placement.js';
export { checkWeaponMasteryUnlocks } from './weapon-mastery.js';
export { updateFactionOnKill, tickFactionPowerForNemeses } from './factions.js';
export { applyRunConsequences, evaluateEventChains } from './world-consequences.js';
export { buildWorldModifiers } from './world-modifiers.js';
//# sourceMappingURL=index.js.map